name: Cherry-pick commit

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: FrogPilot-Testing-newtemp

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Cherry-pick commit
      run: |
        git cherry-pick faa285987daee3e133098ed77d8f3567b183b325
        git push origin HEAD:FrogPilot-Testing-newtemp
